name: Run tests

on:
  push:
    branches:
      - develop
    pull_request:
      branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19.0'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
